image: Visual Studio 2019
skip_commits:
  message: /doco|Merge pull request.*/
build_script:
- cmd: dotnet --version
- cmd: dotnet build --configuration Release
test_script:
  - ps: .\tests.ps1 Release

artifacts:
- path: nugets\**\*.nupkg